name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t karthikeyan/tictactoe
    - name: run flask applicaton && healthchek
      run: docker run --name tictactoe -d -p 8080:8080 karthikeyan/tictactoe && curl --fail http://0.0.0.0:8080 || exit 1
